# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-gha

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      image: ${{ env.IMAGE_NAME }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
#     - name: Pull docker image
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify -e -X

#   test:

#     runs-on: ubuntu-latest

#     steps:
#     - name: Test with Maven
#       run: mvn clean test

