# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Maven version
      uses: s4u/setup-maven-action@v1.6.0
      with:
        java-version: '11'
        maven-version: 3.6.3
    - name: Build with Maven
      run: mvn compile
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Maven version
      uses: s4u/setup-maven-action@v1.6.0
      with:
        java-version: '11'
        maven-version: 3.6.3
    - name: Test with Maven
      run: mvn test
